sequence:
  task: 001.00
  
  sequence:  
    task: 002.00
    task: 002.01
    
  sequence:  
    task: 006.00
    task: 006.01
    
    sequence:  
      task: 006.R0
      
  sequence:  
    task: 004.00
    task: 004.01
    
sequence:
  task: 005.00
  task: 005.01
  task: 005.02
  
  sequence:
    task: 005-R0
    task: 005-R1

   
sequence:
  task: 007.00
  
sequence:
  task: 003.00
  
    
sequence:
  requires: 
    - 006-R
    - 005
    - 001
  task: 011.00
  sequence:
    task: 012.00
  

    
