options:
  increment-version: true
params:
  none: empty
source:
  dir: 001_web-teams/
  route: universe
target:
  dir: 002_timeline-weblikes/
  file: timeline-weblikes_$VERSION$.json
  route: master
version: 1.3
